import { FormEvent, useEffect, useState } from 'react';
import { Button } from '../../components/ui/button';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { FormField } from '../../components/FormField';
import { UserRecord } from './UserDialog';

export function UserPasswordDialog({ open, onOpenChange, user, pending, error, fieldError, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; user?: UserRecord; pending?: boolean; error?: string; fieldError?: string; onSave: (password: string) => void; }) {
  const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [mismatch, setMismatch] = useState(false);
  useEffect(() => { setPassword(''); setConfirmation(''); setMismatch(false); }, [open]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent showCloseButton={false} aria-label="Reset password pengguna" className="max-w-lg p-0"><form onSubmit={(event: FormEvent) => { event.preventDefault(); const invalid = password !== confirmation; setMismatch(invalid); if (!invalid) onSave(password); }}><DialogHeader className="border-b p-5"><DialogTitle>Reset password</DialogTitle><DialogDescription>Tetapkan password baru untuk {user?.full_name}.</DialogDescription></DialogHeader><div className="grid gap-4 p-5"><FormField error={fieldError} label="Password baru" name="password" type="password" minLength={12} required value={password} onChange={(event) => setPassword(event.target.value)} /><FormField label="Konfirmasi password" name="password_confirmation" type="password" minLength={12} required value={confirmation} onChange={(event) => { setConfirmation(event.target.value); setMismatch(false); }} />{mismatch && <p className="text-sm text-destructive" role="alert">Konfirmasi password tidak sama.</p>}{error && <p className="text-sm text-destructive" role="alert">{error}</p>}</div><DialogFooter className="mx-0 mb-0"><DialogClose render={<Button variant="outline" type="button" />}>Batal</DialogClose><Button disabled={pending} type="submit">Simpan password</Button></DialogFooter></form></DialogContent></Dialog>;
}
