import { FormEvent, useEffect, useState } from 'react';
import { Button } from '../../components/ui/button';
import { Checkbox } from '../../components/ui/checkbox';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { FormField } from '../../components/FormField';

export type RegencyOption = { id: string; name: string; document_code: string };
export type Permission = { id: string; code: string; name: string };
export type PermissionGroup = { resource: string; permissions: Permission[] };
export type RoleRecord = { id: string; code: string; name: string; description?: string; is_system: boolean; permissions: Permission[]; all_regencies_access: boolean; regencies: RegencyOption[]; user_count: number };
export type RoleValues = { code: string; name: string; description: string; permission_codes: string[]; all_regencies_access: boolean; regency_ids: string[] };

export function RoleDialog({ open, onOpenChange, groups, regencies, role, pending, error, fields = {}, onSave }: { open: boolean; onOpenChange: (value: boolean) => void; groups: PermissionGroup[]; regencies: RegencyOption[]; role?: RoleRecord; pending?: boolean; error?: string; fields?: Record<string, string>; onSave: (values: RoleValues) => void }) {
  const empty = { code: '', name: '', description: '', permission_codes: [] as string[], all_regencies_access: false, regency_ids: [] as string[] };
  const [values, setValues] = useState<RoleValues>(empty);
  useEffect(() => setValues(role ? { code: role.code, name: role.name, description: role.description ?? '', permission_codes: role.permissions.map((item) => item.code), all_regencies_access: role.all_regencies_access, regency_ids: role.regencies.map((item) => item.id) } : empty), [role, open]);
  const toggle = (code: string) => setValues({ ...values, permission_codes: values.permission_codes.includes(code) ? values.permission_codes.filter((item) => item !== code) : [...values.permission_codes, code] });
  const toggleRegency = (id: string) => setValues({ ...values, regency_ids: values.regency_ids.includes(id) ? values.regency_ids.filter((item) => item !== id) : [...values.regency_ids, id] });
  const title = role ? `Edit ${role.name}` : 'Tambah role';
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent showCloseButton={false} aria-label={title} className="max-h-[calc(100dvh-2rem)] max-w-2xl overflow-y-auto p-0"><form onSubmit={(event: FormEvent) => { event.preventDefault(); onSave(values); }}><DialogHeader className="border-b p-5"><DialogTitle>{title}</DialogTitle><DialogDescription>Pilih hak akses sesuai tanggung jawab.</DialogDescription></DialogHeader><div className="grid gap-4 p-5 sm:grid-cols-2"><FormField error={fields.code} label="Kode role" name="code" required disabled={Boolean(role)} value={values.code} onChange={(event) => setValues({ ...values, code: event.target.value })} /><FormField error={fields.name} label="Nama role" name="name" required value={values.name} onChange={(event) => setValues({ ...values, name: event.target.value })} /><FormField className="sm:col-span-2" error={fields.description} label="Deskripsi" name="description" value={values.description} onChange={(event) => setValues({ ...values, description: event.target.value })} />{groups.map((group) => <fieldset className="grid gap-3 border-0 p-0 sm:col-span-2" key={group.resource}><legend className="mb-2 text-sm font-semibold">{group.resource}</legend>{group.permissions.map((permission) => <label className="flex min-h-11 items-center gap-3" key={permission.code}><Checkbox checked={values.permission_codes.includes(permission.code)} onCheckedChange={() => toggle(permission.code)} />{permission.name}</label>)}</fieldset>)}{fields.permission_codes && <p className="text-sm text-destructive sm:col-span-2" role="alert">{fields.permission_codes}</p>}<fieldset className="grid gap-3 border-0 p-0 sm:col-span-2"><legend className="mb-2 text-sm font-semibold">Akses kabupaten</legend><label className="flex min-h-11 items-center gap-3"><Checkbox checked={values.all_regencies_access} onCheckedChange={(checked) => setValues({ ...values, all_regencies_access: checked === true })} />Akses semua kabupaten</label>{!values.all_regencies_access && regencies.map((regency) => <label className="flex min-h-11 items-center gap-3" key={regency.id}><Checkbox checked={values.regency_ids.includes(regency.id)} onCheckedChange={() => toggleRegency(regency.id)} />{regency.name}</label>)}{fields.regency_ids && <p className="text-sm text-destructive" role="alert">{fields.regency_ids}</p>}</fieldset>{error && <p className="text-sm text-destructive sm:col-span-2" role="alert">{error}</p>}</div><DialogFooter className="mx-0 mb-0"><DialogClose render={<Button type="button" variant="outline" />}>Batal</DialogClose><Button disabled={pending} type="submit">Simpan role</Button></DialogFooter></form></DialogContent></Dialog>;
}
