import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDown, ArrowUp, Eye, EyeOff, FileBadge, ImagePlus, Send } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { DataState } from '@/components/DataState';
import { apiRequest } from '../../lib/api';
import { useCan } from '../../lib/permissions';
import type { DataResponse, DocumentLogo, DocumentProfile, Program } from './types';
import { programTypeLabel } from './types';

const empty = { title: '', subtitle: '', procurement_description: '', document_series: '' };

export function DocumentProfilePanel() {
  const canManage = useCan('programs.manage');
  const client = useQueryClient();
  const [programID, setProgramID] = useState('');
  const [values, setValues] = useState(empty);
  const programs = useQuery({ queryKey: ['program-setup', 'programs'], queryFn: () => apiRequest<DataResponse<Program[]>>('/api/v1/program-setup/programs') });
  useEffect(() => { if (!programID && programs.data?.data[0]) setProgramID(programs.data.data[0].id); }, [programID, programs.data]);
  const profiles = useQuery({ queryKey: ['program-setup', 'programs', programID, 'document-profiles'], queryFn: () => apiRequest<DataResponse<DocumentProfile[]>>(`/api/v1/program-setup/programs/${programID}/document-profiles`), enabled: Boolean(programID) });
  const draft = profiles.data?.data.find((profile) => profile.status === 'draft');
  const current = draft ?? profiles.data?.data[0];
  useEffect(() => { setValues(current ? { title: current.title, subtitle: current.subtitle, procurement_description: current.procurement_description, document_series: current.document_series } : empty); }, [current]);
  const refresh = () => client.invalidateQueries({ queryKey: ['program-setup', 'programs', programID, 'document-profiles'] });
  const save = useMutation({ mutationFn: () => apiRequest(`/api/v1/program-setup/programs/${programID}/document-profiles${draft ? `/${draft.id}` : ''}`, { method: draft ? 'PATCH' : 'POST', body: JSON.stringify(values) }), onSuccess: () => { refresh(); toast.success('Profil dokumen berhasil disimpan.'); }, onError: () => toast.error('Profil dokumen belum dapat disimpan.') });
  const publish = useMutation({ mutationFn: () => apiRequest(`/api/v1/program-setup/programs/${programID}/document-profiles/${draft?.id}/publish`, { method: 'POST' }), onSuccess: () => { refresh(); toast.success('Profil dokumen telah dipublikasikan.'); }, onError: () => toast.error('Profil belum dapat dipublikasikan. Pastikan minimal satu logo aktif.') });
  const uploadLogo = useMutation({ mutationFn: (file: File) => { const body = new FormData(); body.set('file', file); body.set('slot_code', `logo_${(draft?.logos.length ?? 0) + 1}`); body.set('sort_order', String(draft?.logos.length ?? 0)); return apiRequest(`/api/v1/program-setup/programs/${programID}/document-profiles/${draft?.id}/logos`, { method: 'POST', body }); }, onSuccess: () => { refresh(); toast.success('Logo berhasil diunggah.'); }, onError: () => toast.error('Logo belum dapat diunggah.') });
  const updateLogo = useMutation({ mutationFn: ({ logo, patch }: { logo: DocumentLogo; patch: Partial<DocumentLogo> }) => apiRequest(`/api/v1/program-setup/programs/${programID}/document-profiles/${logo.profile_version_id}/logos/${logo.id}`, { method: 'PATCH', body: JSON.stringify({ sort_order: patch.sort_order ?? logo.sort_order, max_width_mm: logo.max_width_mm, max_height_mm: logo.max_height_mm, is_visible: patch.is_visible ?? logo.is_visible }) }), onSuccess: refresh, onError: () => toast.error('Susunan logo belum dapat diperbarui.') });
  const moveLogo = useMutation({ mutationFn: async ({ logo, sibling }: { logo: DocumentLogo; sibling: DocumentLogo }) => { const update = (item: DocumentLogo, sortOrder: number) => apiRequest(`/api/v1/program-setup/programs/${programID}/document-profiles/${item.profile_version_id}/logos/${item.id}`, { method: 'PATCH', body: JSON.stringify({ sort_order: sortOrder, max_width_mm: item.max_width_mm, max_height_mm: item.max_height_mm, is_visible: item.is_visible }) }); await Promise.all([update(logo, sibling.sort_order), update(sibling, logo.sort_order)]); }, onSuccess: refresh, onError: () => toast.error('Urutan logo belum dapat diperbarui.') });
  const selectedProgram = programs.data?.data.find((program) => program.id === programID);

  return <section className="setupPanel" aria-label="Profil dokumen tender">
    <div className="panelHeading"><div><h2><FileBadge />Profil dokumen tender</h2><p>Atur teks dan urutan logo yang akan menjadi header Berita Acara.</p></div></div>
    <div className="grid gap-4 lg:grid-cols-[minmax(240px,0.65fr)_minmax(0,1.35fr)]">
      <Card><CardHeader><CardTitle>Program / tender</CardTitle></CardHeader><CardContent className="space-y-4"><Select value={programID} onValueChange={(value) => setProgramID(value ?? '')}><SelectTrigger aria-label="Program profil dokumen"><SelectValue placeholder="Pilih program" /></SelectTrigger><SelectContent>{programs.data?.data.map((program) => <SelectItem key={program.id} value={program.id}>{program.name}</SelectItem>)}</SelectContent></Select>{selectedProgram && <div className="flex flex-wrap gap-2"><Badge>{programTypeLabel(selectedProgram.program_type)}</Badge><Badge variant="outline">{selectedProgram.code}</Badge></div>}<div className="space-y-2 border-t pt-4"><p className="text-sm font-medium">Riwayat versi</p>{profiles.data?.data.map((profile) => <div key={profile.id} className="flex items-center justify-between rounded-md border px-3 py-2 text-sm"><span>Versi {profile.version}</span><Badge variant={profile.status === 'published' ? 'default' : 'outline'}>{profile.status === 'published' ? 'Terbit' : 'Draf'}</Badge></div>)}</div></CardContent></Card>
      {profiles.isPending ? <DataState kind="loading" title="Memuat profil dokumen" description="Mengambil konfigurasi tender dan logo." /> : profiles.isError ? <DataState kind="error" title="Profil dokumen belum dapat dimuat" description="Periksa koneksi lalu coba kembali." action={{ label: 'Coba lagi', onClick: () => profiles.refetch() }} /> : <div className="space-y-4">
        <Card><CardHeader><CardTitle>{draft ? `Draf versi ${draft.version}` : current ? `Versi ${current.version} telah terbit` : 'Buat profil pertama'}</CardTitle></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="grid gap-2"><Label htmlFor="profile-title">Judul</Label><Input id="profile-title" value={values.title} onChange={(event) => setValues({ ...values, title: event.target.value })} disabled={!canManage} required /></div><div className="grid gap-2"><Label htmlFor="profile-subtitle">Subjudul</Label><Input id="profile-subtitle" value={values.subtitle} onChange={(event) => setValues({ ...values, subtitle: event.target.value })} disabled={!canManage} /></div><div className="grid gap-2 sm:col-span-2"><Label htmlFor="profile-procurement">Deskripsi pengadaan</Label><textarea id="profile-procurement" className="min-h-24 rounded-lg border bg-background px-3 py-2 text-sm" value={values.procurement_description} onChange={(event) => setValues({ ...values, procurement_description: event.target.value })} disabled={!canManage} required /></div><div className="grid gap-2"><Label htmlFor="profile-series">Seri dokumen</Label><Input id="profile-series" value={values.document_series} onChange={(event) => setValues({ ...values, document_series: event.target.value.toUpperCase() })} disabled={!canManage} placeholder="KSM-KKT" required /></div>{canManage && <div className="flex items-end"><Button type="submit" disabled={save.isPending}>Simpan draf</Button></div>}</form></CardContent></Card>
        {draft && <Card><CardHeader><CardTitle>Logo header</CardTitle><p className="text-sm text-muted-foreground">PNG transparan atau JPEG, maksimal 10 MiB.</p></CardHeader><CardContent className="space-y-4">{canManage && <label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-lg border px-4 text-sm font-medium hover:bg-muted"><ImagePlus className="size-4" />Unggah logo<input className="sr-only" aria-label="Unggah logo" type="file" accept="image/png,image/jpeg" onChange={(event) => { const file = event.target.files?.[0]; if (file) uploadLogo.mutate(file); }} /></label>}<div className="grid gap-3 sm:grid-cols-2">{draft.logos.map((logo, index) => <div key={logo.id} className="flex items-center gap-3 rounded-lg border p-3"><div className="grid size-20 place-items-center rounded-md bg-muted p-2"><img className={`max-h-full max-w-full object-contain ${logo.is_visible ? '' : 'opacity-35'}`} src={logo.content_url} alt={logo.original_filename} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{logo.original_filename}</p><p className="text-xs text-muted-foreground">Urutan {index + 1}</p>{canManage && <div className="mt-2 flex gap-1"><Button size="icon-sm" variant="outline" aria-label={`Naikkan ${logo.original_filename}`} disabled={index === 0 || moveLogo.isPending} onClick={() => moveLogo.mutate({ logo, sibling: draft.logos[index - 1] })}><ArrowUp /></Button><Button size="icon-sm" variant="outline" aria-label={`Turunkan ${logo.original_filename}`} disabled={index === draft.logos.length - 1 || moveLogo.isPending} onClick={() => moveLogo.mutate({ logo, sibling: draft.logos[index + 1] })}><ArrowDown /></Button><Button size="icon-sm" variant="outline" aria-label={`${logo.is_visible ? 'Sembunyikan' : 'Tampilkan'} ${logo.original_filename}`} onClick={() => updateLogo.mutate({ logo, patch: { is_visible: !logo.is_visible } })}>{logo.is_visible ? <EyeOff /> : <Eye />}</Button></div>}</div></div>)}</div>{canManage && <div className="flex justify-end border-t pt-4"><Button onClick={() => { if (window.confirm('Publikasikan profil ini? Versi terbit tidak dapat diubah.')) publish.mutate(); }} disabled={!draft.logos.some((logo) => logo.is_visible) || publish.isPending}><Send />Publikasikan versi</Button></div>}</CardContent></Card>}
      </div>}
    </div>
  </section>;
}
