import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Camera, Edit3, PackageCheck, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { DataTable } from '../../components/DataTable';
import { FormField } from '../../components/FormField';
import { apiRequest } from '../../lib/api';
import { useCan } from '../../lib/permissions';
import { SetupDialog } from './SetupDialog';
import { DataResponse, DocumentationSlot, DocumentationTemplate, PackageTemplate, ProgramType, programTypeLabel } from './types';

const newSlot = (index = 0): DocumentationSlot => ({ slot_code: '', label: '', stage: 'distribution', is_required: true, min_files: 1, max_files: 1, input_source: 'both', require_location: false, require_captured_at: false, sort_order: (index + 1) * 10 });

export function TemplatesPanel() {
  const canManage = useCan('programs.manage'); const client = useQueryClient();
  const packages = useQuery({ queryKey: ['program-setup', 'package-templates'], queryFn: () => apiRequest<DataResponse<PackageTemplate[]>>('/api/v1/program-setup/package-templates') });
  const documents = useQuery({ queryKey: ['program-setup', 'documentation-templates'], queryFn: () => apiRequest<DataResponse<DocumentationTemplate[]>>('/api/v1/program-setup/documentation-templates') });
  const [packageOpen, setPackageOpen] = useState(false); const [packageEditing, setPackageEditing] = useState<PackageTemplate>();
  const [packageValues, setPackageValues] = useState({ template_code: '', name: '', program_type: 'farmer' as ProgramType, status: 'draft', values: '{}' });
  const [documentOpen, setDocumentOpen] = useState(false); const [documentEditing, setDocumentEditing] = useState<DocumentationTemplate>();
  const [documentValues, setDocumentValues] = useState({ template_code: '', name: '', program_type: 'farmer' as ProgramType, status: 'draft', slots: [newSlot()] });
  const packageMutation = useMutation({ mutationFn: () => apiRequest(`/api/v1/program-setup/package-templates${packageEditing ? `/${packageEditing.id}` : ''}`, { method: packageEditing ? 'PATCH' : 'POST', body: JSON.stringify({ ...packageValues, values: JSON.parse(packageValues.values) }) }), onSuccess: () => { setPackageOpen(false); client.invalidateQueries({ queryKey: ['program-setup', 'package-templates'] }); } });
  const documentMutation = useMutation({ mutationFn: () => apiRequest(`/api/v1/program-setup/documentation-templates${documentEditing ? `/${documentEditing.id}` : ''}`, { method: documentEditing ? 'PATCH' : 'POST', body: JSON.stringify(documentValues) }), onSuccess: () => { setDocumentOpen(false); client.invalidateQueries({ queryKey: ['program-setup', 'documentation-templates'] }); } });
  const showPackage = (item?: PackageTemplate) => { setPackageEditing(item); setPackageValues(item ? { template_code: item.template_code, name: item.name, program_type: item.program_type, status: item.status, values: JSON.stringify(item.values, null, 2) } : { template_code: '', name: '', program_type: 'farmer', status: 'draft', values: '{}' }); setPackageOpen(true); };
  const showDocument = (item?: DocumentationTemplate) => { setDocumentEditing(item); setDocumentValues(item ? { template_code: item.template_code, name: item.name, program_type: item.program_type, status: item.status, slots: item.slots } : { template_code: '', name: '', program_type: 'farmer', status: 'draft', slots: [newSlot()] }); setDocumentOpen(true); };
  const updateSlot = (index: number, patch: Partial<DocumentationSlot>) => setDocumentValues({ ...documentValues, slots: documentValues.slots.map((slot, slotIndex) => slotIndex === index ? { ...slot, ...patch } : slot) });
  return <div className="templateGrid"><section className="setupPanel"><header className="panelHeading"><div><h2><PackageCheck />Template paket</h2><p>Nilai baku komponen yang disalin ke setiap alokasi.</p></div>{canManage && <button className="primaryButton" onClick={() => showPackage()}><Plus />Tambah paket</button>}</header>
    {packages.data?.data.length ? <DataTable label="Template paket"><thead><tr><th>Template</th><th>Jenis</th><th>Versi</th><th>Status</th>{canManage && <th>Aksi</th>}</tr></thead><tbody>{packages.data.data.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small className="subline">{item.template_code}</small></td><td>{programTypeLabel(item.program_type)}</td><td>v{item.version}</td><td>{item.status}</td>{canManage && <td><button className="iconButton" aria-label={`Edit ${item.name}`} onClick={() => showPackage(item)}><Edit3 /></button></td>}</tr>)}</tbody></DataTable> : <div className="emptyState">Belum ada template paket.</div>}
  </section><section className="setupPanel"><header className="panelHeading"><div><h2><Camera />Template dokumentasi</h2><p>Slot foto dapat berbeda untuk setiap jenis program.</p></div>{canManage && <button className="primaryButton" onClick={() => showDocument()}><Plus />Tambah dokumentasi</button>}</header>
    {documents.data?.data.length ? <DataTable label="Template dokumentasi"><thead><tr><th>Template</th><th>Jenis</th><th>Versi</th><th>Slot</th><th>Status</th>{canManage && <th>Aksi</th>}</tr></thead><tbody>{documents.data.data.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small className="subline">{item.template_code}</small></td><td>{programTypeLabel(item.program_type)}</td><td>v{item.version}</td><td>{item.slots.length}</td><td>{item.status}</td>{canManage && <td><button className="iconButton" aria-label={`Edit ${item.name}`} onClick={() => showDocument(item)}><Edit3 /></button></td>}</tr>)}</tbody></DataTable> : <div className="emptyState">Belum ada template dokumentasi.</div>}
    </section>
    <SetupDialog open={packageOpen} onOpenChange={setPackageOpen} title={packageEditing ? `Edit ${packageEditing.name}` : 'Tambah template paket'} description="Perubahan pada versi published akan membuat draft versi baru." pending={packageMutation.isPending} onSubmit={() => packageMutation.mutate()}>
      <FormField label="Kode template" name="package_code" required disabled={Boolean(packageEditing)} value={packageValues.template_code} onChange={(e) => setPackageValues({ ...packageValues, template_code: e.target.value.toUpperCase() })} />
      <FormField label="Nama template" name="package_name" required value={packageValues.name} onChange={(e) => setPackageValues({ ...packageValues, name: e.target.value })} />
      <label className="formField"><span>Jenis program</span><select className="selectField" value={packageValues.program_type} onChange={(e) => setPackageValues({ ...packageValues, program_type: e.target.value as ProgramType })}><option value="farmer">Petani</option><option value="fisherman">Nelayan</option></select></label>
      <label className="formField"><span>Status</span><select className="selectField" value={packageValues.status} onChange={(e) => setPackageValues({ ...packageValues, status: e.target.value })}><option value="draft">Draft</option><option value="published">Published</option><option value="retired">Retired</option></select></label>
      <label className="formField fullField"><span>Nilai paket</span><textarea className="jsonField" rows={10} value={packageValues.values} onChange={(e) => setPackageValues({ ...packageValues, values: e.target.value })} /><small>Struktur JSON menyimpan merek, tipe, komponen, jumlah, dan satuan.</small></label>
      {packageMutation.isError && <p className="formNotice">Template paket belum dapat disimpan. Periksa format nilai paket.</p>}
    </SetupDialog>
    <SetupDialog open={documentOpen} onOpenChange={setDocumentOpen} title={documentEditing ? `Edit ${documentEditing.name}` : 'Tambah template dokumentasi'} description="Perubahan pada versi published akan membuat draft versi baru." pending={documentMutation.isPending} onSubmit={() => documentMutation.mutate()}>
      <FormField label="Kode template" name="document_code" required disabled={Boolean(documentEditing)} value={documentValues.template_code} onChange={(e) => setDocumentValues({ ...documentValues, template_code: e.target.value.toUpperCase() })} />
      <FormField label="Nama template" name="document_name" required value={documentValues.name} onChange={(e) => setDocumentValues({ ...documentValues, name: e.target.value })} />
      <label className="formField"><span>Jenis program</span><select className="selectField" value={documentValues.program_type} onChange={(e) => setDocumentValues({ ...documentValues, program_type: e.target.value as ProgramType })}><option value="farmer">Petani</option><option value="fisherman">Nelayan</option></select></label>
      <label className="formField"><span>Status</span><select className="selectField" value={documentValues.status} onChange={(e) => setDocumentValues({ ...documentValues, status: e.target.value })}><option value="draft">Draft</option><option value="published">Published</option><option value="retired">Retired</option></select></label>
      <div className="slotEditor fullField"><div className="slotEditorHead"><strong>Slot dokumentasi</strong><button type="button" className="secondaryButton" onClick={() => setDocumentValues({ ...documentValues, slots: [...documentValues.slots, newSlot(documentValues.slots.length)] })}><Plus />Tambah slot</button></div>{documentValues.slots.map((slot, index) => <div className="slotRow" key={index}><FormField label="Kode slot" name={`slot_code_${index}`} required value={slot.slot_code} onChange={(e) => updateSlot(index, { slot_code: e.target.value.toLowerCase() })} /><FormField label="Judul" name={`slot_label_${index}`} required value={slot.label} onChange={(e) => updateSlot(index, { label: e.target.value })} /><label className="formField"><span>Sumber</span><select className="selectField" value={slot.input_source} onChange={(e) => updateSlot(index, { input_source: e.target.value as DocumentationSlot['input_source'] })}><option value="both">Kamera & galeri</option><option value="camera">Kamera</option><option value="gallery">Galeri</option></select></label><FormField label="Minimal" name={`slot_min_${index}`} type="number" min={0} value={slot.min_files} onChange={(e) => updateSlot(index, { min_files: Number(e.target.value) })} /><label className="checkboxField"><input type="checkbox" checked={slot.is_required} onChange={(e) => updateSlot(index, { is_required: e.target.checked })} />Wajib</label><button type="button" className="iconButton dangerIcon" aria-label={`Hapus slot ${slot.label || index + 1}`} onClick={() => setDocumentValues({ ...documentValues, slots: documentValues.slots.filter((_, slotIndex) => slotIndex !== index) })}><Trash2 /></button></div>)}</div>
      {documentMutation.isError && <p className="formNotice">Template dokumentasi belum dapat disimpan.</p>}
    </SetupDialog>
  </div>;
}
